version: "3"
services:
  application:
    image: spring-boot-mysql-application
    ports:
      - "8080:8080"
    networks:
      - springboot-db-networks
    depends_on:
      - mysqldb
    volumes:
      - /data/spring-boot-mysql-application
    
  mysqldb:
    image: mysql:5.7
    networks:
      - springboot-db-networks
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sbms
    volumes:
      - /data/mysql
networks:
  springboot-db-networks:
